version: api/v1
kind: BPConfigmap
metadata:
  name: payment-gateway-pre-prod
spec:
  is_deploy: False
  manifest_meta_data:
    strategy: GIT_MANIFEST
    manifest_file_paths:
      - "./configmap/payment-gateway-pre-prod.yaml"
    manifest_git_repo: ot-micro-salary
    manifest_git_repo_branch: helm-chart
  application_env_namespace:
    application_env:
      application: payments
      environment_master: staging
      name: pre-prod
    namespace:
      cluster: ot-aws-cluster
      name: dev
