version: api/v1
kind: BPConfigmap
metadata:
  name: redis-v2-pre-prod
spec:
  is_deploy: False
  manifest_meta_data:
    strategy: GIT_MANIFEST
    manifest_file_paths:
      - "."
    manifest_git_repo: okts-redis
    manifest_git_repo_branch: master
  application_env_namespace:
    application_env:
      application: web-logic
      environment_master: staging
      name: pre-prod
    namespace:
      cluster: ot-aws-cluster
      name: dev
